# Programmieraufgabe 1: Matrix-Matrix-Multiplikation

## Einleitung

Die Matrix-Matrix-Multiplikation $C=AB$ der Matrizen $A\in \mathbb{R}^{m\times n}$,
$B\in \mathbb{R}^{n\times p}$ lässt sich auf unterschiedliche Art und Weise interpretieren:

- eine Sequenz von Matrix-(Spalten)Vektor-Multiplikationen: $c^{j} = A b^{j}$,
- eine Sequenz von (Zeilen)Vektor-Matrix-Multiplikationen: $c_{i}^T = a_{i}^T B$,
- eine Sequenz von inneren Produkten: $c_{i}^{j} = a_{i}^T b^{j}$,
- [eine Sequenz von äußeren Produkten: $C =  \sum_{0\le k < n} a^{k} b_{k}^T$],
- komponentenweise Berechnung: $c_{i}^{j} =  \sum_{0\le k < n} a_{i}^{k} b_{k}^{j}$.

Hier geben die Indizes die Zeilen- bzw. die Spaltennummer an. Wir nutzen $i$ für Zeilen und $j$ für Spalten.

In Python werden Matrixdatenstrukturen von `numpy` zur Verfügung gestellt und man
kann Matrix-Matrix-Multiplikation mit `C=A@B` und Matrix-Vektor-Multiplikation
mit `c=A@b` ausführen. 

Auf den Eintrag $(i,j)$ von $A$ kann man mit `A[i,j]` zugreifen.
Auf die Zeile $i$ von $A$ kann man mit `A[i,:]` und
auf die Spalte $j$ von $A$ kann man mit `A[:,j]` zugreifen.

Implementieren Sie Matrix-Matrix-Multiplikationvarianten in Python, indem Sie die richtigen
Funktionen aus `numpy` nutzen. Untersuchen Sie für verschiedene Problemgrößen
die Performance der Implementierungen (Zeitmessung mit dem Paket `time` und Visualisierung mit `matplotlib.pyplot`). Was fällt ihnen auf? Was könnte der 
Grund sein?
Wie ist die Performance
verglichen mit der Implementierung Matrix-Matrix-Multiplikation von `numpy`?

Zur Abgabe beachten Sie bitte die Hinweise in `HinweisePython.pdf` und nutzen Sie folgendes Jupyter notebook.

## Vorbereitung

Wir nutzen das `numpy` Paket. Bitte importieren Sie es als `np`:

In [2]:
import numpy as np

Erstellen Sie eine zufällige Matriz der Größe `4x5` mit den Namen `A_test` und eine zufällige Matriz der Größe `5x3` mit den Namen `B_test`, führen Sie eine Matrix-Matrix-Multiplikation aus und speichern Sie das Ergebnis in `C_test`.

In [3]:
A_test = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]])
print(A_test)
B_test =  np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12],
                   [13, 14, 15]])
print(B_test)
C_test = A_test @ B_test

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


Geben Sie den Inhalt von `C_test` aus.

In [4]:
print(C_test)

[[135 150 165]
 [310 350 390]
 [485 550 615]
 [660 750 840]]


## Matrix-Matrix-Multiplikation

### Version 1: Sequenz von Matrix-(Spalten)Vektor-Multiplikationen

Implementieren Sie eine Matrix-Matrix-Multiplikation durch eine Sequenz von Matrix-(Spalten)Vektor-Multiplikationen.

In [5]:
def version1(A, B):
    C = np.zeros((A.shape[0], B.shape[1]))
    for j in range(B.shape[1]):
        C[:, j] = (A @ B[:, j])
    return C

Die folgende Funktion nutzen wir zum Prüfen des Outputs der zu erstellenden Funktionen.

In [6]:
def compare_matrices(M1, M2):

    diff_matr = np.absolute(M1-M2)
    max_error = np.max(diff_matr)
    success   =  max_error < 1e-8

    if success:
        print("Matrix comparison successful!")
    else:
        print("Matrix comparison failed!")

Prüfen wir die Korrektheit der Funktion `version1`.

In [7]:
compare_matrices(C_test, version1(A_test,B_test))

Matrix comparison successful!


### Version 2: Sequenz von (Zeilen)Vektor-Matrix-Multiplikationen

Implementieren Sie eine Matrix-Matrix-Multiplikation durch eine Sequenz von (Zeilen)Vektor-Matrix-Multiplikationen.

In [8]:
def version2(A, B):
    C = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        C[i ,:] = A[i ,:] @ B
    return C

Prüfen wir die Korrektheit der Funktion `version2`.

In [9]:
compare_matrices(C_test, version2(A_test,B_test))

Matrix comparison successful!


### Version 3: Sequenz von inneren Produkten

Implementieren Sie eine Matrix-Matrix-Multiplikation durch eine Sequenz von inneren Produkten.

In [10]:
def version3(A, B):  
    C = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            C[i, j] = np.dot(A[i ,:], B[:, j])
        
    return C

Prüfen wir die Korrektheit der Funktion `version3`.

In [11]:
compare_matrices(C_test, version3(A_test,B_test))

Matrix comparison successful!


### Version 4: komponentenweise Berechnung

Implementieren Sie eine Matrix-Matrix-Multiplikation durch eine komponentenweise Berechnung.

In [12]:
def version4(A, B):  
    C = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                C[i, j] += A[i, k] * B[k, j]
    return C

Prüfen wir die Korrektheit der Funktion `version4`.

In [13]:
compare_matrices(C_test, version4(A_test,B_test))

Matrix comparison successful!


## Performancevergleich

Im Folgenden betrachten wir die Performance der verschiedenen Matrix-Matrix-Multiplikationsimplementierungen.

Als Vergleich nutzen wir die Implementierung von `numpy`:

In [14]:
def version5(A, B):
    C = A@B
    return C

Das folgende Skript führt die Implementierungen für verschiedene Problemgrößen aus, misst die Ausführungszeiten und plottet die Zeiten.

In [ ]:
import time
import matplotlib.pyplot as plt

max_matrix_size = 100

ss = [10, 20, 50, 100, 200, 500, 1000]
ss = [i for i in ss if i <= max_matrix_size]

time1 = []
time2 = []
time3 = []
time4 = []
time5 = [] 

def my_timer(mult):
    start = time.time()
    for i in range(0,10):
        mult(A, B)
    end = time.time()
    return end - start

for s in ss:
    m = s
    n = s
    p = s

    A = np.zeros((m, n))
    B = np.zeros((p, n))
    C = np.zeros((m, p))

    time1 = time1 + [my_timer(version1)]
    time2 = time2 + [my_timer(version2)]
    time3 = time3 + [my_timer(version3)]
    time4 = time4 + [my_timer(version4)]
    time5 = time5 + [my_timer(version5)] 

plt.plot(ss, time1, label='v1')
plt.plot(ss, time2, label='v2')
plt.plot(ss, time3, label='v3')
plt.plot(ss, time4, label='v4')
plt.plot(ss, time5, label='np') 

plt.xscale('log')
plt.yscale('log')
plt.xlabel('m=n=p')
plt.ylabel('time')
plt.legend()
plt.grid()
plt.show()

Sie können die maximal Matrixgröße im Code durch die Modifikation des Parameters `max_matrix_size` erhöhen. Bitte vergessen Sie nicht die langsamste Implementierung zu deaktivieren.